spring.application.name=learning

server.port=8080

## Add Embedding model
spring.ai.ollama.base-url=${REMOTE_LLM_HOST}
spring.ai.ollama.chat.options.model=llama3.2
spring.ai.ollama.embedding.options.model=nomic-embed-text

## Define Vector Store properties
spring.ai.vectorstore.pgvector.dimensions=1024
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE

## JDBC Properties
spring.datasource.url=jdbc:postgresql://localhost:5432/rag_demo
spring.datasource.username=user
spring.datasource.password=password
